theme = "catppuccin_mocha_alpha"

[editor]
line-number = "relative"
true-color=true
cursorline=true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints=true

[editor.indent-guides]
render=true
